services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: coingecko_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  parser:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: coingecko_db
      DB_USER: user
      DB_PASSWORD: password
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: